In [93]:
import pandas as pd
import numpy as np
import pickle
career = pd.read_csv('dataset_skills.csv', header = None)

In [94]:
career.head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0   5   5   5   5   1   5   9   5   5   5   5   5   5   5   5   5   5   
1   6   6   6   6   6   6   6   6   6   9   6   6   6   6   2   6   6   
2   6   5   6   6   6   9   6   6   6   6   6   6   6   6   6   6   6   
3   7   7   7   7   7   7   7   7   7   7   7   7   7   9   7   2   2   
4   9   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   

                           17  
0              API Specialist  
1            Technical Writer  
2          Software Developer  
3  Customer Service Executive  
4      Database Administrator

In [95]:
X = np.array(career.iloc[:, 0:17]) #X is skills
print(X)
y = np.array(career.iloc[:, 17]) #Y is Roles
print("hi")
print(y) 

[[5 5 5 ... 5 5 5]
 [6 6 6 ... 2 6 6]
 [6 5 6 ... 6 6 6]
 ...
 [9 7 7 ... 7 5 5]
 [6 6 9 ... 6 6 6]
 [2 2 2 ... 2 2 9]]
hi
['API Specialist' 'Technical Writer' 'Software Developer' ...
 'Database Administrator' 'Application Support Engineer'
 'Graphics Designer']


In [96]:
career.columns = ["Database Fundamentals","Computer Architecture","Distributed Computing Systems",
"Cyber Security","Networking","Development","Programming Skills","Project Management",
"Computer Forensics Fundamentals","Technical Communication","AI ML","Software Engineering","Business Analysis",
"Communication skills","Data Science","Troubleshooting skills","Graphics Designing","Roles"]

career.dropna(how ='all', inplace = True)

In [97]:
career.head()

Database Fundamentals  Computer Architecture  \
0                      5                      5   
1                      6                      6   
2                      6                      5   
3                      7                      7   
4                      9                      2   

   Distributed Computing Systems  Cyber Security  Networking  Development  \
0                              5               5           1            5   
1                              6               6           6            6   
2                              6               6           6            9   
3                              7               7           7            7   
4                              2               2           2            2   

   Programming Skills  Project Management  Computer Forensics Fundamentals  \
0                   9                   5                                5   
1                   6                   6                                6   
2                   6                   6                                6   
3                   7                   7                                7   
4                   2                   2                                2   

   Technical Communication  AI ML  Software Engineering  Business Analysis  \
0                        5      5                     5                  5   
1                        9      6                     6                  6   
2                        6      6                     6                  6   
3                        7      7                     7                  7   
4                        2      2                     2                  2   

   Communication skills  Data Science  Troubleshooting skills  \
0                     5             5                       5   
1                     6             2                       6   
2                     6             6                       6   
3                     9             7                       2   
4                     2             2                       2   

   Graphics Designing                       Roles  
0                   5              API Specialist  
1                   6            Technical Writer  
2                   6          Software Developer  
3                   2  Customer Service Executive  
4                   2      Database Administrator

In [98]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state = 524)
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
scores = {}
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)
print('X_train',X_train)
print('y_train',y_train)
y_pred = knn.predict(X_test)
print('y_pred',y_pred)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

pickle.dump(knn, open('knn_model.pkl','wb'))
print('test file created')

X_train [[9 7 7 ... 7 7 7]
 [3 7 7 ... 7 7 7]
 [1 1 9 ... 1 1 1]
 ...
 [6 6 6 ... 6 6 6]
 [3 3 3 ... 3 3 3]
 [1 1 1 ... 1 9 1]]
y_train ['Database Administrator' 'Technical Writer'
 'Application Support Engineer' ... 'API Specialist' 'Business Analyst'
 'Helpdesk Engineer']
y_pred ['AI ML Specialist' 'Information Security Specialist'
 'Information Security Specialist' ... 'AI ML Specialist' 'Data Scientist'
 'Technical Writer']
0.9673202614379085
test file created
